---
#
# Playbook to install the ELK stack + Beats
#
- hosts: all
  remote_user: vagrant
  become: yes
  become_user: root
  roles:
  - { role: java, tags: java }
  - { role: elasticsearch, tags: elasticsearch }
  - { role: kibana, tags: kibana }
  - { role: logstash, tags: logstash }
  - { role: filebeat, tags: filebeat }
