---
# Installing Kibana
- name: Installing Kibana
  yum: name=https://artifacts.elastic.co/downloads/kibana/kibana-7.6.1-x86_64.rpm

##Template kibana
- name: Template a file to /etc/kibana/kibana.yml
  template:
    src: ../templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: elasticsearch
    mode: '0660'    
  
##Changing owner /etc/kibana/kibana.yml
- name: Change ownership /etc/kibana
  file:
    path: /etc/kibana
    state: directory
    recurse: yes
    owner: kibana
    group: elasticsearch 

# Starting Kibana
- name: Starting Kibana
  service:
   name: kibana
   state: started
