---
# Install java
- name: Install java-1.8.0-openjdk
  yum:
   name: "{{ packages }}"
   state: present
  vars:
    packages:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - java-1.8.0-openjdk-headless
